config/routes.rb
Rails.application.routes.draw do
  get '/users/count', to: 'users#count'
  get '/users/:id/name', to: 'users#name'
  get 'users/edit', to: 'users#multiple_edit'
  resources :users do
    resource :shop
  end

end

app/models/shop.rb
class Shop
  include Mongoid::Document
  include Mongoid::Timestamps
  belongs_to :user
  field :name, type: String
end

app/models/user.rb
class User
    include Mongoid::Document
    include Mongoid::Timestamps

    has_one :shop

    field :first_name, type: String
    field :last_name, type: String
    field :gender, type: String
    field :age, type: Integer
    field :address, type: Hash

    validates :first_name, :last_name, presence: true
    validates :gender, inclusion: { in: %w(male female others) }
    validates :age, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # test comment
  protect_from_forgery with: :exception
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :user, only: [:create]
  before_action :set_shop, only: [:show, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /users/:user_id/shop
  # GET /users/:user_id/shop.json
  def show
  end

  # POST /users/:user_id/shop
  # POST /users/:user_id/shop.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @user and @user.shop.nil? and @shop.save
        @user.shop = @shop
        format.json { render :show, status: :ok, location: user_shop_path(@shop) }
      else
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/:user_id/shop
  # PATCH/PUT /users/:user_id/shop
  def update
    respond_to do |format|
      if @shop and @shop.update(shop_params)
        format.json { render :show, status: :ok, location: user_shop_path(@shop) }
      else
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/:user_id/shop
  # DELETE /users/:user_id/shop.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = User.find(params[:user_id]).shop
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name)
    end

    def user
      @user = User.find(params[:user_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :name]
  skip_before_action :verify_authenticity_token

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /users/count
  def count
    @count = User.count
  end

  # GET /user/1/name
  def name
  end

  # GET /users/edit
  def multiple_edit
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :gender, :age, address: [:county, :address_1, :address_2])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blank</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="angularExample">

<%= yield %>

</body>
</html>

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<%= link_to 'Edit', edit_user_shop_path(@shop) %> |
<%= link_to 'Back', user_shop_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Create Users</h1>

<div class="container">
  <div ng-controller="UsersCtrl">

    <div class="row" ng-init="getUser()">
      <div class="col-md-12">
        <form name="createForm" novalidate>
          <div>
            <label for=name>first name</label>
            <input ng-model="newUserInfo.firstName" type="text" name="firstName" required>
            <div ng-show="createForm.firstName.$invalid">first name is required</div>
          </div>

          <div>
            <label for=name>last name</label>
            <input ng-model="newUserInfo.lastName" type="text" name="lastName" required>
            <div ng-show="createForm.lastName.$invalid">last name is required</div>
          </div>

          <div>
            <label for=name>age</label>
            <input ng-model="newUserInfo.age" type="text" name="age" pattern="^[1-9]\d*$">
            <div ng-show="createForm.age.$invalid">age is not positive number</div>
          </div>

          <div>
            <label for=name>gender</label>
            <input ng-model="newUserInfo.gender" type="text" name="gender" pattern="\b(male|female|others)\b" required>
            <div ng-show="createForm.gender.$invalid">not a legal gender</div>
          </div>

          <input id="create" type="button" value="submit" ng-disabled="createForm.$invalid" ng-click="createUser(newUserInfo)" />
        </form>

        <h1>Listing Users</h1>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="col-md-3">first name</th>
              <th class="col-md-2">last name</th>
              <th class="col-md-2">age</th>
              <th class="col-md-2">gender</th>
            </tr>
          </thead>
          <tbody>
            <tr ng-repeat="user in data">
              <td>{{user.first_name}}</td>
              <td>{{user.last_name}}</td>
              <td>{{user.age}}</td>
              <td>{{user.gender}}</td>
              <td>
                <input id="edit" type="button" value="edit" ng-click="showHide(user)">
              </td>
              <td>
                <input id="delete" type="button" value="delete" ng-click="deleteUser(user)">
              </td>
              <td ng-user="" ng-show="user.display"></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/multiple_edit.html.erb
<h1>edit users page</h1>
<div class="container">
  <div ng-controller="UsersCtrl">

    <div class="row" ng-init="getUser()">
      <div class="col-md-12">
        <table>
          <thead>
            <th class="col-md-3">first name</th>
            <th class="col-md-2">last name</th>
            <th class="col-md-2">age</th>
            <th class="col-md-2">gender</th>
          </thead>
          <tbody>
            <td><input ng-model="newUserInfo.firstName" type="text" class="form-control" name="firstName" required /></td>
            <td><input ng-model="newUserInfo.lastName" type="text" class="form-control" name="lastName"></td>
            <td><input ng-model="newUserInfo.age" type="number" class="form-control" name="age" required></td>
            <td><input ng-model="newUserInfo.gender" type="text" class="form-control" name="gender"></td>
            <td><input type="submit" ng-click="createUser(newUserInfo)"></td>
          </tbody>
        </table>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="col-md-3">first name</th>
              <th class="col-md-2">last name</th>
              <th class="col-md-2">age</th>
              <th class="col-md-2">gender</th>
            </tr>
          </thead>
          <tbody>
            <tr ng-repeat="user in data">
              <td>{{user.first_name}}</td>
              <td>{{user.last_name}}</td>
              <td>{{user.age}}</td>
              <td>{{user.gender}}</td>
              <td ng-user="">
              </td>
            </tr>
          </tbody>
        </table>
        <%# <table ng-user=""></table> %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>